# Generated by Django 3.2.12 on 2023-09-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpages', '0002_alter_client_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
    ]
