# Generated by Django 3.2.12 on 2023-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpages', '0003_inventory_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expirated',
            field=models.BooleanField(default=False),
        ),
    ]
