# Generated by Django 3.2.12 on 2023-09-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpages', '0005_servicepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='plate_code',
            field=models.CharField(max_length=7),
        ),
    ]
