# Generated by Django 4.2.6 on 2023-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpages', '0008_serviceticket_car_serviceticket_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='car',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_date',
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
